name: Build and Push Docker Image to GHCR

# Define triggers for the workflow: push to a tag or main branch
on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Extract the version tag if this is a tag push
      - name: Extract version tag
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Set 'latest' tag if pushing to the main branch
      - name: Set default tag to latest
        if: github.ref == 'refs/heads/main'
        run: echo "VERSION_TAG=latest" >> $GITHUB_ENV

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image with a temporary tag
      - name: Build Docker image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $DOCKER_IMAGE:temp .

      # Push the Docker image using the version tag, or 'latest' if on main branch
      - name: Tag and push the versioned image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:temp $DOCKER_IMAGE:${{ env.VERSION_TAG }}
          docker push $DOCKER_IMAGE:${{ env.VERSION_TAG }}

      # Optionally, also tag as 'latest' for main branch or any version tag
      - name: Tag and push 'latest'
        if: github.ref == 'refs/heads/main' || startsWith(env.VERSION_TAG, 'v')
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:temp $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest

      # Optionally, also tag and push the 'v1' tag for all 'v1.x.x' versions
      - name: Tag and push 'v1' for major version releases
        if: startsWith(env.VERSION_TAG, 'v1.')
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:temp $DOCKER_IMAGE:v1
          docker push $DOCKER_IMAGE:v1

      # Log out of GitHub Container Registry
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io