name: Build and Push Docker Image, Create Release on Tagged Commits

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags (e.g., v1.0.0, v2.1.0)
    branches:
      - main   # Trigger when pushing to the main branch

permissions:
  contents: write     # Allows creating a release
  packages: write     # Allows pushing packages to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for git log

      # Step 2: Set version tag and commit SHA, and decide between versioned tag or 'latest'
      - name: Set version tag and commit SHA
        id: set_version_and_commit
        run: |
          # If pushing to a version tag, extract the tag version
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi

          # Short form of the commit SHA
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build the Docker image once using the commit SHA
      - name: Build Docker image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $DOCKER_IMAGE:${{ env.COMMIT_SHA }} .

      # Step 5: Push the Docker image tagged with the commit SHA
      - name: Push image with commit SHA
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker push $DOCKER_IMAGE:${{ env.COMMIT_SHA }}

      # Step 6: Optionally, tag and push the image based on the version tag or 'latest'
      - name: Tag and push version or latest tag
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:${{ env.COMMIT_SHA }} $DOCKER_IMAGE:${{ env.VERSION_TAG }}
          docker push $DOCKER_IMAGE:${{ env.VERSION_TAG }}

      # Step 7: Optionally, tag and push the major version (e.g., v1, v2)
      - name: Tag and push major version if versioned release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          MAJOR_VERSION=$(echo "${{ env.VERSION_TAG }}" | grep -oE '^v[0-9]+')
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:${{ env.COMMIT_SHA }} $DOCKER_IMAGE:${MAJOR_VERSION}
          docker push $DOCKER_IMAGE:${MAJOR_VERSION}

      # Step 8: Handle version tagged releases by generating release notes if it's a version tag
      - name: Collect commit messages since last version tag
        if: startsWith(github.ref, 'refs/tags/')
        id: generate_release_notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
          RELEASE_NOTES=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s" --no-merges)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Step 9: Create a GitHub release with the commit messages if it's a version tag
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: "Release ${{ env.VERSION_TAG }}"
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false

      # Step 10: Log out from the GitHub Container Registry
      - name: Log out from GHCR
        run: docker logout ghcr.io