name: Build and Push Docker Image to GHCR

# Controls when the workflow will run
on:
  # Trigger on creation of tags (e.g. v1.0.0)
  push:
    tags:
      - 'v*'
    branches:
      - main

# Permissions for GITHUB_TOKEN
permissions:
  contents: read          # Allows reading access to the repository content
  packages: write         # Allows pushing to the GitHub Container Registry (GHCR)

# Setup jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Extract the version tag if this is a tag push (e.g., v1.0.0)
      - name: Extract version tag
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Set default to 'latest' if pushing to main branch
      - name: Set default version tag to latest
        if: github.ref == 'refs/heads/main'
        run: echo "VERSION_TAG=latest" >> $GITHUB_ENV

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image using the version tag or 'latest'
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.VERSION_TAG }}
          docker build -t $IMAGE_NAME .

      # Push the Docker image to GitHub Container Registry with tag (version or latest)
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.VERSION_TAG }}
          docker push $IMAGE_NAME

      # Tag the image as `latest` if this is a version tag
      - name: Tag and push the latest version (optional)
        if: startsWith(env.VERSION_TAG, 'v')
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.VERSION_TAG }}
          LATEST_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker tag $IMAGE_NAME $LATEST_IMAGE
          docker push $LATEST_IMAGE

      # Create a 'v1' tag for all v1.x.x versions
      - name: Tag and push v1 version
        if: startsWith(env.VERSION_TAG, 'v1.')
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.VERSION_TAG }}
          V1_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:v1
          docker tag $IMAGE_NAME $V1_IMAGE
          docker push $V1_IMAGE

      # Log out from GitHub Container Registry, optional cleanup step
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io