name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - 'v*'    # Trigger on version tags (e.g., v1.0.0, v1.1.0)
    branches:
      - main    # Trigger on push to the `main` branch

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract the version tag if this is a tag push (e.g., `v1.2.0`)
      - name: Extract version tag
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 3: Set the tag to 'latest' if pushing to the main branch
      - name: Set default tag to 'latest'
        if: github.ref == 'refs/heads/main'
        run: echo "VERSION_TAG=latest" >> $GITHUB_ENV

      # Step 4: Log in to the GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Build the Docker image. Only one build will occur.
      - name: Build Docker image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $DOCKER_IMAGE:${{ env.VERSION_TAG }} .

      # Step 6: Push the image using the Versioned Tag or 'latest' if on main
      - name: Push the Docker image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker push $DOCKER_IMAGE:${{ env.VERSION_TAG }}

      # Step 7: Optionally, tag and push 'latest' for main branch or version tags.
      - name: Tag and push 'latest'
        if: github.ref == 'refs/heads/main' || startsWith(env.VERSION_TAG, 'v')
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:${{ env.VERSION_TAG }} $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest

      # Step 8: Optionally, tag and push 'v1' for major version releases (e.g. `v1.x.x`)
      - name: Tag and push 'v1' for major version releases
        if: startsWith(env.VERSION_TAG, 'v1.')
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:${{ env.VERSION_TAG }} $DOCKER_IMAGE:v1
          docker push $DOCKER_IMAGE:v1

      # Step 9: Log out of the GitHub Container Registry
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io