name: Build and Push Docker Image without Duplicates, Create Release

on:
  push:
    tags:
      - 'v*'    # Trigger on version tags (e.g., v1.0.0)
    branches:
      - main    # Trigger when pushing to the main branch

permissions:
  contents: write     # Allow creating releases
  packages: write     # Allow pushing to GitHub Container Registry (GHCR)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history including tags

      # Step 2: Set version tag and commit SHA
      - name: Set version tag and commit SHA
        id: set_version_and_commit
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build the Docker image once using the commit SHA
      - name: Build Docker image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $DOCKER_IMAGE:${{ env.COMMIT_SHA }} .

      # Step 5: Push the Docker image tagged with the commit SHA
      - name: Push the Docker image with commit SHA
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker push $DOCKER_IMAGE:${{ env.COMMIT_SHA }}

      # Step 6: Tag the image (already built with commit SHA) with `latest` or version tag and push it
      - name: Tag and Push Latest or Version
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          # Tag and push with the version or latest tag
          docker tag $DOCKER_IMAGE:${{ env.COMMIT_SHA }} $DOCKER_IMAGE:${{ env.VERSION_TAG }}
          docker push $DOCKER_IMAGE:${{ env.VERSION_TAG }}

      # Step 7: Tag missing major version (e.g., `v1` or `v2`) and push it
      - name: Tag and Push Major Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          MAJOR_VERSION=$(echo "${{ env.VERSION_TAG }}" | grep -oE '^v[0-9]+')
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}
          docker tag $DOCKER_IMAGE:${{ env.COMMIT_SHA }} $DOCKER_IMAGE:${MAJOR_VERSION}
          docker push $DOCKER_IMAGE:${MAJOR_VERSION}

      # Step 8: Generate the release notes for version tags ONLY
      - name: Generate Release Notes
        if: startsWith(github.ref, 'refs/tags/')
        id: generate_release_notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
          RELEASE_NOTES=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s" --no-merges)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Step 9: Create a release on GitHub with the commit messages
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: "Release ${{ env.VERSION_TAG }}"
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false

      # Step 10: Log out from GitHub Container Registry (GHCR)
      - name: Log out from GHCR
        run: docker logout ghcr.io