name: Build and Push Docker Image to GHCR

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Setup jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker build -t $IMAGE_NAME .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker push $IMAGE_NAME

      # Log out from GitHub Container Registry, optional cleanup step
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
        
permissions:
  contents: read          # Read access to the repository content
  packages: write         # Write access to GitHub Container Registry